### ISSUE TITLE
PUT image/png : operation timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by jmettraux** [toland/patron#12]
details at :

http://gist.github.com/313391

(the gist uses a simple sinatra server, but the issue was initially observed with CouchDB)

symptom :

    $ ruby client.rb
    /Users/jmettraux/.rvm/gems/ruby-1.9.1-p378/gems/patron-0.4.5/lib/patron/session.rb:179:in `handle_request': Operation timed out after 5000 milliseconds with 0 bytes received (Patron::TimeoutError)
    from /Users/jmettraux/.rvm/gems/ruby-1.9.1-p378/gems/patron-0.4.5/lib/patron/session.rb:179:in `request'
    from /Users/jmettraux/.rvm/gems/ruby-1.9.1-p378/gems/patron-0.4.5/lib/patron/session.rb:127:in `put'
    from client.rb:10:in `<main>'

Many thanks for Patron !

**Comment by julik** [comment]
Reproduced, I will look into this.

**Comment by julik** [comment]
This problem occurs with any request body that is 32 bytes long or more. @toland is there any buffering thing at the C level that would cause something like this to happen that you remember?

**Comment by toland** [comment]
@julik Not that I remember. It has been a looong time since I worked with that code, and some other contributors have made changes in that area. I just looked at the C code again and it was like looking at something someone else wrote :)
