### ISSUE TITLE
Automate the Patron release process

### ISSUE THREAD

**Issue by toland** [toland/patron#137]
The series of steps to create a Patron release and push to rubygems.org are simple and begging to be automated.
1. `git pull origin master`
2. Update `lib/patron/version.rb`
3. `bundle`
4. `git commit -m "Release <version>"`
5. `git tag -a <version> -m <version>`
6. `git push origin master && git push --tags`
7. `rake build`
8. `gem push`

**Comment by julik** [comment]
FWIW Jeweler is working for me for all my gems but it does introduce dependencies (including the one on git, which in turn depends on nokogiri, which in turn... so it _is_ a circle of terrible).

**Comment by toland** [comment]
I used Jeweler some way back in the day; I will take another look at it. Thanks for the pointer.

**Comment by toland** [comment]
For reference, Jeweler is here: https://github.com/technicalpickles/jeweler

It is currently unmaintained. See https://github.com/technicalpickles/jeweler/issues/283

The issue comments list some alternatives.

**Comment by julik** [comment]
I've moved quite a few of my gems to the bundler newgem workflow and it works well, however most of my gems do not have C extensions. I will investigate how we could adapt this for Patron.

**Comment by toland** [comment]
Awesome.
