### ISSUE TITLE
Cookies are not saved

### ISSUE THREAD

**Issue by Grundik** [toland/patron#15]
When an Patron:Session handle_cookies option is set, cookies are not saved into a specified file. I have investigated this problem and found that cookies are read correctly, but not saved due to incomplete session_ext.so cleanup (probably).

Workaround for this problem is here: http://ololo.cc/files/cookiejar.patch
Fix description: cookies are dumped after every successful request. Required libcurl 7.17.1+

**Comment by julik** [comment]
Thanks for the patch, that was a quickie! Only 4+ years ;-) but nevertheless.
