### ISSUE TITLE
Charset coercion enhancements

### ISSUE THREAD

**Issue by toland** [toland/patron#51]
The current charset coercion code, while nice, can be a bit heavy handed and is just wrong in certain circumstances. In order to get ready for 1.0 I would like to add the following enhancements:

* Make coercion optional and off by default
* Allow the user to set a list of Content-Types that should be coerced (default to "text/*")
* Allow the user to set a fallback charset if the charset provided by the server is unknown or none is provided

**Comment by julik** [comment]
@toland do you have a WIP from this issue? I would like to revisit the charset handling part but had a few questions on semantics.

**Comment by toland** [comment]
@julik Unfortunately, I do not. I lost that branch when the hard drive in my laptop died. That is one of the reasons I never finished that work.

**Comment by julik** [comment]
Being worked on in https://github.com/toland/patron/pull/122
