### ISSUE TITLE
JRuby: undefined symbol: rb_set_end_proc

### ISSUE THREAD

**Issue by prawin** [toland/patron#54]
I am usgin jruby 1.6.2 on RVM. The gem got installed correctly but consle doesnt starts up throws 
`java: symbol lookup error: /home/prawin/.rvm/gems/jruby-1.6.2/gems/patron-0.4.17/lib/patron/session_ext.so: undefined symbol: rb_set_end_proc`

**Comment by julik** [comment]
Don't see any reference to `rb_set_end_proc` in the current source, only `rb_ensure`. Also quite some water went under the bridge in jRuby land since then (like the extraction of C extension support), so closing.
