### ISSUE TITLE
Unable to share session across threads.

### ISSUE THREAD

**Issue by jacobsimeon** [toland/patron#74]
Should a `Patron::Session` be threadsafe? I am seeing an error while trying to use the same session in multiple threads.

Here is my test script:
``` ruby
  require 'patron'

  sess = Patron::Session.new
  sess.base_url = "http://sushi.com"
  sess.insecure = true

  threads = [0, 1].map do |i|
    Thread.start do
      sess.get("/nigiri/sake.json")
    end
  end

  threads.each { |t| t.join }
```

And this is the stacktrace:
```
/Users/jacobmorris/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/patron-0.4.18/lib/patron/session.rb:223:in `handle_request': CURLOPT_SSL_VERIFYHOST no longer supports 1 as value! (Patron::Error)
	from /Users/jacobmorris/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/patron-0.4.18/lib/patron/session.rb:223:in `request'
	from /Users/jacobmorris/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/patron-0.4.18/lib/patron/session.rb:126:in `get'
	from lib/tasks/search.rake:38:in `block (2 levels) in do_raw_patron_test'
```

The weird thing is that this code does not cause the same exception:

``` ruby
  sess = Patron::Session.new
  sess.base_url = "http://sushi.com"
  sess.insecure = true

  sess.get("/nigiri/sake.json")
```

If the real issue is setting SSL_VERIFYHOST with an incorrect value, shouldn't the exception be raised in both cases? 

What is the expected behavior of using the same session from multiple threads?

**Comment by totallymike** [comment]
This still appears to be an issue

**Comment by julik** [comment]
Would it be a good thing to just note that a Session is not meant to be shared between threads? IMO, a CURL handle is something that should be subject to an explicit external resource pooling, instead of providing built-in thread safety guarantees.

**Comment by julik** [comment]
@totallymike would that work if the threading behavior would be documented?

**Comment by totallymike** [comment]
I suspect that would help quite a bit.  It's been some time since I've worked on the project in which I used patron, so I've lost a bit of context.

**Comment by julik** [comment]
There is now a section in the README describing the recommended approach to multithreading, and it advizes the usage of connection_pool, which should work fine. Thank you for your report!
