### ISSUE TITLE
Push latest gem releases

### ISSUE THREAD

**Issue by tmandry** [toland/patron#81]
Good to see some activity and new releases on this repo. One of those releases contains a fix I've been waiting for (data in DELETE requests); is there anything holding you back from pushing this to RubyGems?

**Comment by julik** [comment]
Is this issue still relevant? I see 0.5.0 was released past September

**Comment by toland** [comment]
It doesn't look like this is relevant any longer. Everything that was pending has been released.

**Comment by karmi** [comment]
Hi @toland, many thanks for that!
