### ISSUE TITLE
Update the 0.4.20 tag

### ISSUE THREAD

**Issue by benhanzl** [toland/patron#87]
I'm unsure of what code is included in the 0.4.20 tag. On [RubyGems](https://rubygems.org/gems/patron) the latest version is 0.4.20 released February 20, 2015, but the tag was created Jul 24, 2014.

**Comment by toland** [comment]
The released gem contains everything that is on master. That having been said, there is only one small code change since the tag was made and everything else is changes to the build system or readme file.

**Comment by toland** [comment]
I have created a new tag and a new release to remove any confusion.
